In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
# 한글 찍기
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':
    rc('font', family = 'AppleGothic')
elif platform.system() == 'Windows':
    rc('font', family = 'Malgun Gothic')   # 또는 '맑은 고딕'
else:
    print('Unknown system... sorry~~~~')

import warnings
warnings.filterwarnings('ignore')

In [16]:
CCTV_Seoul = pd.read_csv('./datas/CCTV_in_Seoul.csv')
CCTV_Seoul = CCTV_Seoul.rename(columns={'기관명':'구별'})
CCTV_Seoul.head(2)

    구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377

In [13]:
pop_Seoul = pd.read_excel('./datas/population_in_Seoul.xls',
                         header=2,    
                         usecols='B, D, G, J, N') 
pop_Seoul.columns = [ '구별', '인구수', '한국인', '외국인', '고령자' ]
pop_Seoul.head(2)

    구별         인구수        한국인       외국인        고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0

In [17]:
new_data = pd.merge(CCTV_Seoul, pop_Seoul, on='구별')
new_data.head()

,구별,소계,2013년도 이전,2014년,2015년,2016년,인구수,한국인,외국인,고령자
0,강남구,2780,1292,430,584,932,570500.0,565550.0,4950.0,63167.0
1,강동구,773,379,99,155,377,453233.0,449019.0,4214.0,54622.0
2,강북구,748,369,120,138,204,330192.0,326686.0,3506.0,54813.0
3,강서구,884,388,258,184,81,603772.0,597248.0,6524.0,72548.0
4,관악구,1496,846,260,390,613,525515.0,507203.0,18312.0,68082.0

In [19]:
sb.scatterplot(
    data=new_data, 
    x='인구수', 
    y='CCTV갯수',
    hue='지역구',        # 👈 지역구별로 색상 다르게
    size='외국인비율',    # 👈 점 크기를 외국인비율로
    style='구별',      # 👈 점 모양도 다르게
    palette='viridis'   # 👈 색상 테마
)

ValueError: Could not interpret value `CCTV갯수` for `y`. An entry with this name does not appear in `data`.