# 지도에 좌표 표시하기
- 위도 latitude : lat
- 경도 longtitude : lot

In [1]:
import folium

In [2]:
#디폴트 위도/경도 지점(focusing), 지도 사이트인 map객체를 생성
folium.Map(location=[37.5662952, 126.9779451], zoom_start=16)

In [4]:
#zoom_start의 size가 작을수록 zoom-out된 상태에서 시작
folium.Map(location=[37.5662952, 126.9779451], zoom_start=5)

In [6]:
folium_map = folium.Map(location=[37.5662952, 126.9779451], zoom_start=16)
folium.Marker(location=[37.5662952, 126.9779451]).add_to(folium_map) #메모리에 씌우기

In [14]:
#클릭했을 때 '서울시청 위치'가 뜨도록 특정 지도 지점에 팝업을 꼽는 방법
popup = folium.Popup('서울시청 위치', max_width=300)
folium.Marker(location=[37.5662952, 126.9779451], popup=popup).add_to(folium_map)
folium_map

In [13]:
import os
os.makedirs('map_data', exist_ok=True)
folium_map.save('map_data/folium_map.html')

In [18]:
#밀라노 근무지 가져와보기 #우왕
folium.Map(location=[45.48380673469669, 9.189731092247902], zoom_start=20)

- 스타벅스 실습의 경우에는, 원래는 open source였는디, 안되니까 생략!

In [28]:
import requests
import folium
# from pandas.io.json import json_normalize <-- 아래와 같이 수정
from pandas import json_normalize

In [29]:
# 스벅 위치 데이터 가져오기
targetSite='https://www.starbucks.co.kr/store/getStore.do?r=8K3XF06R9Q'
req=requests.post(targetSite, data={
'ins_lat': 37.563398,    # 위도
'ins_lng': 126.9863309,  # 경도
'p_sido_cd': '01',
'p_gugun_cd': '',
'in_biz_cd': '',
'iend': 300,   # 300개
'set_date': ''
})

In [30]:
starbucks=req.json()

In [31]:
print(type(starbucks))
print(starbucks.keys())

<class 'dict'>
dict_keys(['list'])

**[tip] json_normalize(starbucks, 'list') 의미**
- 'list' 키의 데이터를 df로 만들어줌

In [33]:
data= {
    "status": "success",
    "count": 5,
    "list": [
        {"store_id": "001", "name": "Store A", "location": "Seoul"},
        {"store_id": "002", "name": "Store B", "location": "Busan"}
    ]
}
data

{'status': 'success',
 'count': 5,
 'list': [{'store_id': '001', 'name': 'Store A', 'location': 'Seoul'},
  {'store_id': '002', 'name': 'Store B', 'location': 'Busan'}]}

In [34]:
result = json_normalize(data, 'list')
result

  store_id     name location
0      001  Store A    Seoul
1      002  Store B    Busan

In [35]:
starbucks_df=json_normalize(starbucks, 'list')
starbucks_df

,seq,sido_cd,sido_nm,gugun_cd,gugun_nm,code_order,view_yn,store_num,sido,gugun,...,t30,t36,t27,t29,t43,t48,z9999,t64,t66,p02
0,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
1,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
2,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
3,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
4,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
296,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
297,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
298,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
299,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0

In [36]:
# df 정보 보기
# starbucks_df.info()
starbucks_df.info(verbose=True, memory_usage='deep', show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 137 columns):
 #    Column                   Non-Null Count  Dtype
---   ------                   --------------  -----
 0    seq                      300 non-null    int64
 1    sido_cd                  0 non-null      object
 2    sido_nm                  0 non-null      object
 3    gugun_cd                 0 non-null      object
 4    gugun_nm                 0 non-null      object
 5    code_order               0 non-null      object
 6    view_yn                  0 non-null      object
 7    store_num                0 non-null      object
 8    sido                     0 non-null      object
 9    gugun                    0 non-null      object
 10   address                  0 non-null      object
 11   new_img_nm               0 non-null      object
 12   p_pro_seq                300 non-null    int64
 13   p_view_yn                0 non-null      object
 14   p_sido_cd                300 non-null    object
 15   p_gugun_cd               300 non-null    object
 16   p_store_nm               0 non-null      object
 17   p_theme_cd               0 non-null      object
 18   p_wireless_yn            0 non-null      object
 19   p_smoking_yn             0 non-null      object
 20   p_book_yn                0 non-null      object
 21   p_music_yn               0 non-null      object
 22   p_terrace_yn             0 non-null      object
 23   p_table_yn               0 non-null      object
 24   p_takeout_yn             0 non-null      object
 25   p_parking_yn             0 non-null      object
 26   p_dollar_assent          0 non-null      object
 27   p_card_recharge          0 non-null      object
 28   p_subway_yn              0 non-null      object
 29   stb_store_file_renew     0 non-null      object
 30   stb_store_theme_renew    0 non-null      object
 31   stb_store_time_renew     0 non-null      object
 32   stb_store_lsm            0 non-null      object
 33   s_code                   300 non-null    object
 34   s_name                   300 non-null    object
 35   tel                      300 non-null    object
 36   dlvry_call_cntr_phno     0 non-null      object
 37   fax                      300 non-null    object
 38   sido_code                300 non-null    object
 39   sido_name                300 non-null    object
 40   gugun_code               300 non-null    object
 41   gugun_name               300 non-null    object
 42   addr                     300 non-null    object
 43   park_info                0 non-null      object
 44   new_state                106 non-null    object
 45   theme_state              300 non-null    object
 46   new_bool                 300 non-null    int64
 47   search_text              300 non-null    object
 48   ins_lat                  300 non-null    object
 49   ins_lng                  300 non-null    object
 50   in_distance              300 non-null    int64
 51   out_distance             300 non-null    object
 52   all_search_cnt           300 non-null    int64
 53   addr_search_cnt          300 non-null    int64
 54   store_search_cnt         300 non-null    int64
 55   rowCount                 300 non-null    int64
 56   store_nm                 300 non-null    object
 57   store_cd                 300 non-null    int64
 58   s_biz_code               300 non-null    object
 59   new_icon                 300 non-null    object
 60   set_user                 300 non-null    object
 61   favorites                300 non-null    int64
 62   map_desc                 0 non-null      object
 63   notice                   0 non-null      object
 64   defaultimage             300 non-null    object
 65   etcimage                 0 non-null      object
 66   in_biz_cd                0 non-null      object
 67   in_store_cd              0 non-null      object
 68   in_favorites             0 non-null      object
 69   in_user_id               0 non-null      object
 70   in_biz_cds               300 non-null    int64
 71   in_biz_arr               0 non-null      object
 72   in_biz_arrdata           0 non-null      object
 73   in_scodes                300 non-null    int64
 74   in_scode_arr             0 non-null      object
 75   in_scode_arrdata         0 non-null      object
 76   disp                     0 non-null      object
 77   set_date                 0 non-null      object
 78   hlytag                   0 non-null      object
 79   hlytag_msg               0 non-null      object
 80   vSal                     300 non-null    object
 81   istart                   300 non-null    int64
 82   iend                     300 non-null    int64
 83   open_dt                  300 non-null    object
 84   gold_card                300 non-null    int64
 85   ip_lat                   300 non-null    object
 86   ip_long                  300 non-null    object
 87   espresso                 300 non-null    object
 88   new_store                300 non-null    object
 89   premiere_food            300 non-null    object
 90   doro_address             300 non-null    object
 91   cold_blew                300 non-null    object
 92   my_siren_order_store_yn  300 non-null    object
 93   whcroad_yn               300 non-null    object
 94   skuNo                    300 non-null    object
 95   skuName                  300 non-null    object
 96   skuImgUrl                300 non-null    object
 97   stock_count              300 non-null    int64
 98   store_area_name          0 non-null      object
 99   store_area_code          300 non-null    object
 100  is_open                  0 non-null      object
 101  ev_open_yn               0 non-null      object
 102  option                   0 non-null      object
 103  gift_stock_yn            0 non-null      object
 104  lat                      300 non-null    object
 105  lot                      300 non-null    object
 106  t20                      300 non-null    int64
 107  t04                      300 non-null    int64
 108  t03                      300 non-null    int64
 109  t01                      300 non-null    int64
 110  t12                      300 non-null    int64
 111  t09                      300 non-null    int64
 112  t06                      300 non-null    int64
 113  t10                      300 non-null    int64
 114  p10                      300 non-null    int64
 115  p50                      300 non-null    int64
 116  p20                      300 non-null    int64
 117  p60                      300 non-null    int64
 118  p30                      300 non-null    int64
 119  p70                      300 non-null    int64
 120  p40                      300 non-null    int64
 121  p80                      300 non-null    int64
 122  t22                      300 non-null    int64
 123  t21                      300 non-null    int64
 124  p90                      300 non-null    int64
 125  p01                      300 non-null    int64
 126  t05                      300 non-null    int64
 127  t30                      300 non-null    int64
 128  t36                      300 non-null    int64
 129  t27                      300 non-null    int64
 130  t29                      300 non-null    int64
 131  t43                      300 non-null    int64
 132  t48                      300 non-null    int64
 133  z9999                    300 non-null    int64
 134  t64                      300 non-null    int64
 135  t66                      300 non-null    int64
 136  p02                      300 non-null    int64
dtypes: int64(47), object(90)
memory usage: 1.2 MB

In [37]:
starbucks_df.columns

Index(['seq', 'sido_cd', 'sido_nm', 'gugun_cd', 'gugun_nm', 'code_order',
       'view_yn', 'store_num', 'sido', 'gugun',
       ...
       't30', 't36', 't27', 't29', 't43', 't48', 'z9999', 't64', 't66', 'p02'],
      dtype='object', length=137)

In [38]:
cols = ['s_name','sido_code','sido_name','gugun_code','gugun_name', 'doro_address','lat','lot']
starbucks_df_map=starbucks_df[cols]
starbucks_df_map.head(3)

,s_name,sido_code,sido_name,gugun_code,gugun_name,doro_address,lat,lot
0,역삼아레나빌딩,01,서울,0101,강남구,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,논현역사거리,01,서울,0101,강남구,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,신사역성일빌딩,01,서울,0101,강남구,서울특별시 강남구 강남대로 584 (논현동),37.5139309,127.0206057

In [39]:
# 위도, 경도 숫자로 변경
starbucks_df_map.loc[:, 'lat']=starbucks_df_map['lat'].astype(float)
starbucks_df_map.loc[:, 'lot']=starbucks_df_map['lot'].astype(float)

In [45]:
starbucks_df_map.head(3)

,s_name,sido_code,sido_name,gugun_code,gugun_name,doro_address,lat,lot
0,역삼아레나빌딩,01,서울,0101,강남구,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,논현역사거리,01,서울,0101,강남구,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,신사역성일빌딩,01,서울,0101,강남구,서울특별시 강남구 강남대로 584 (논현동),37.513931,127.020606

In [70]:
# 지도에 표현하기 일단 1개 실습
# step1. 일단 데이터에 starbucksMap이란 걸 넣어놓기
starbucksMap=folium.Map(location=[37.501087,127.043069], zoom_start=16)
# step2. 팝업 설정
popup=folium.Popup('역삼아레나빌딩점', max_width=300)
euksam_location = [starbucks_df_map[starbucks_df_map['s_name'] == '역삼아레나빌딩']['lat'].values[0],
                   starbucks_df_map[starbucks_df_map['s_name'] == '역삼아레나빌딩']['lot'].values[0]]
folium.Marker(location= euksam_location, popup=popup).add_to(starbucksMap)
starbucksMap

In [ ]:
popup=folium.Popup('종각점', max_width=300)

In [ ]:
folium.Marker(location=[37.569918, 126.984528], popup=popup).add_to(starbucksMap)
popup=folium.Popup('종로관철점', max_width=300)
folium.Marker(location=[37.569058, 126.986013], popup=popup).add_to(starbucksMap)
popup=folium.Popup('종로구청점', max_width=300)
folium.Marker(location=[37.572662, 126.981138], popup=popup).add_to(starbucksMap)

In [ ]:
print(starbucks_df_map[starbucks_df_map['s_name'] == '종각점'])

# [문제] 위에 있는 모든 지역을 지도에 표현하기

In [65]:
starbucks_df_map.head(3)

,s_name,sido_code,sido_name,gugun_code,gugun_name,doro_address,lat,lot
0,역삼아레나빌딩,01,서울,0101,강남구,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,논현역사거리,01,서울,0101,강남구,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,신사역성일빌딩,01,서울,0101,강남구,서울특별시 강남구 강남대로 584 (논현동),37.513931,127.020606

-  s_name, lat, lot 컬럼 추출

In [68]:
starbucks_map2 = starbucks_df_map[['s_name','lat','lot']]
starbucks_map2.head()

    s_name        lat         lot
0  역삼아레나빌딩  37.501087  127.043069
1   논현역사거리  37.510178  127.022223
2  신사역성일빌딩  37.513931  127.020606
3   국기원사거리  37.499517  127.031495
4   대치재경빌딩  37.494668  127.062583

- 데이터 프레임의 values만 추출

In [69]:
s_map_datas = starbucks_map2.values
s_map_datas[:5]

array([['역삼아레나빌딩', 37.501087, 127.043069],
       ['논현역사거리', 37.510178, 127.022223],
       ['신사역성일빌딩', 37.5139309, 127.0206057],
       ['국기원사거리', 37.499517, 127.031495],
       ['대치재경빌딩', 37.494668, 127.062583]], dtype=object)

### 지도에 표현하기

In [71]:
s_map_datas[0][1]

37.501087

In [72]:
len(s_map_datas)

300

In [77]:
# 지도 객체 생성
foliumMap=folium.Map(location=[s_map_datas[0][1], s_map_datas[0][2]], zoom_start=16)

#저장할 폴더 생성
os.makedirs('folium_data', exist_ok=True)

# map에 표시하기
n=0
for n in range(len(s_map_datas)):
    popup=folium.Popup(s_map_datas[n][0], max_width=300)
    folium.Marker(location=[s_map_datas[n][1],s_map_datas[n][2]], popup=popup).add_to(foliumMap)
    
# 지도 파일로 저장
foliumMap.save('folium_data/folium_map1.html')
# foliumMap 객체 반환
foliumMap

In [ ]:
#유정언니의 for문

# for item in s_map_datas:
#     store_name = item[0]
#     lat = item[1]
#     lon = item[2]
    
#     popup=folium.Popup(f"스타벅스 {store_name}점", max_width=300)

#     folium.Marker(
#             location=[lat, lon]
#             popup=popup
#         ).add_to(folium_map)

In [ ]:
#강사님의 for문